version: '3'

services:
  app:
    build:
      args:
        user: bulletin_board
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: bulletin_board
    container_name: ${APP_NAME}_app
    restart: unless-stopped
    working_dir: /var/www/bulletin_board
    volumes:
      - ./:/var/www/bulletin_board
    networks:
      - bulletin_board
    depends_on:
      - db
      - nginx
      - redis
      - node
      - rabbitmq
  db:
    image: postgres
    container_name: ${APP_NAME}_db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./storage/pg-data:/var/lib/postgresql/data"
      #- ./docker-compose/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - bulletin_board
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}_nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www/bulletin_board
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - bulletin_board
  redis:
    image: 'redis'
    container_name: ${APP_NAME}_redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
        - '6379:6379'
    volumes:
        - './storage/redis-data:/data'
    networks:
        - bulletin_board
  node:
    image: "node:12"
    container_name: ${APP_NAME}_node
    user: "node"
    working_dir: /home/node/app/bulletin_board
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app/bulletin_board
    expose:
      - "8081"
    command: bash -c "npm install && npm run watch"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${APP_NAME}_rabbitmq
    volumes:
      #- ./docker-compose/rabbitmq/etc/:/etc/rabbitmq/
      - ./storage/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker-compose/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - bulletin_board
  queue:
    image: bulletin_board
    container_name: ${APP_NAME}_queue
    restart: unless-stopped
    working_dir: /var/www/bulletin_board
    command: php artisan queue:work
    volumes:
      - ./:/var/www/bulletin_board
    networks:
      - bulletin_board
    depends_on:
      - app
networks:
  bulletin_board:
    driver: bridge
